"""patient conditions

Revision ID: 0f32b5776a50
Revises: 52a045ca73cb
Create Date: 2026-09-26 19:05:29.322555
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0f32b5776a50"
down_revision: str | None = "52a045ca73cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patient_conditions",
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("raw_text", sa.String(length=500), nullable=False),
        sa.Column("category_code", sa.String(length=50), nullable=True),
        sa.Column("visit_type", sa.String(length=20), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_patient_conditions_category_code"),
        "patient_conditions",
        ["category_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patient_conditions_patient_id"), "patient_conditions", ["patient_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_patient_conditions_patient_id"), table_name="patient_conditions")
    op.drop_index(op.f("ix_patient_conditions_category_code"), table_name="patient_conditions")
    op.drop_table("patient_conditions")
    # ### end Alembic commands ###
