"""tasks leads scripts campaigns

Revision ID: 9327585693d6
Revises: 5fc0390e31aa
Create Date: 2026-09-26 20:13:49.398993
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9327585693d6"
down_revision: str | None = "5fc0390e31aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaigns",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("segment", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("script_code", sa.String(length=30), nullable=True),
        sa.Column("daily_limit", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "active",
                "paused",
                "finished",
                name="campaignstatus",
                native_enum=False,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column("ends_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_campaigns_status"), "campaigns", ["status"], unique=False)
    op.create_table(
        "scripts",
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column(
            "language",
            sa.Enum("uz", "ru", name="language", native_enum=False, length=5),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", "language"),
    )
    op.create_index(op.f("ix_scripts_code"), "scripts", ["code"], unique=False)
    op.create_table(
        "shift_notes",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shift_notes_created_at"), "shift_notes", ["created_at"], unique=False)
    op.create_table(
        "leads",
        sa.Column("patient_id", sa.Uuid(), nullable=True),
        sa.Column("phone", sa.String(length=16), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column(
            "channel",
            sa.Enum(
                "call",
                "missed_call",
                "website",
                "telegram",
                "instagram",
                "walk_in",
                "manual",
                name="leadchannel",
                native_enum=False,
                length=15,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "instagram",
                "telegram",
                "google",
                "maps",
                "website",
                "recommendation",
                "advertising",
                "returning",
                "import",
                "cold_base",
                "other",
                name="source",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("interest", sa.Text(), nullable=True),
        sa.Column(
            "stage",
            sa.Enum(
                "new",
                "contacted",
                "booked",
                "visited",
                "later",
                "lost",
                name="leadstage",
                native_enum=False,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column("lost_reason", sa.String(length=50), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("sla_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_response_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("appointment_id", sa.Uuid(), nullable=True),
        sa.Column("external_id", sa.String(length=100), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["appointment_id"], ["appointments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_index(op.f("ix_leads_channel"), "leads", ["channel"], unique=False)
    op.create_index(op.f("ix_leads_patient_id"), "leads", ["patient_id"], unique=False)
    op.create_index(op.f("ix_leads_phone"), "leads", ["phone"], unique=False)
    op.create_index(op.f("ix_leads_sla_due_at"), "leads", ["sla_due_at"], unique=False)
    op.create_index(op.f("ix_leads_stage"), "leads", ["stage"], unique=False)
    op.create_table(
        "tasks",
        sa.Column(
            "type",
            sa.Enum(
                "confirm_visit",
                "missed_call",
                "new_lead",
                "lost_lead",
                "no_show",
                "repeat_visit",
                "post_procedure",
                "course_continue",
                "reactivation",
                "campaign",
                "callback",
                name="tasktype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("open", "done", "cancelled", name="taskstatus", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("priority", sa.SmallInteger(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=True),
        sa.Column("lead_id", sa.Uuid(), nullable=True),
        sa.Column("appointment_id", sa.Uuid(), nullable=True),
        sa.Column("recommendation_id", sa.Uuid(), nullable=True),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("script_code", sa.String(length=30), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum(
                "booked",
                "confirmed",
                "rescheduled",
                "cancelled",
                "refused",
                "thinking",
                "callback",
                "no_answer",
                "wrong_number",
                "do_not_call",
                "done",
                name="outcome",
                native_enum=False,
                length=15,
            ),
            nullable=True,
        ),
        sa.Column("outcome_reason", sa.String(length=50), nullable=True),
        sa.Column("dedupe_key", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["appointment_id"], ["appointments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["completed_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(["recommendation_id"], ["recommendations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    op.create_index(op.f("ix_tasks_campaign_id"), "tasks", ["campaign_id"], unique=False)
    op.create_index(op.f("ix_tasks_due_at"), "tasks", ["due_at"], unique=False)
    op.create_index(op.f("ix_tasks_lead_id"), "tasks", ["lead_id"], unique=False)
    op.create_index(op.f("ix_tasks_patient_id"), "tasks", ["patient_id"], unique=False)
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_index(op.f("ix_tasks_type"), "tasks", ["type"], unique=False)
    op.create_table(
        "task_attempts",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column(
            "task_type",
            sa.Enum(
                "confirm_visit",
                "missed_call",
                "new_lead",
                "lost_lead",
                "no_show",
                "repeat_visit",
                "post_procedure",
                "course_continue",
                "reactivation",
                "campaign",
                "callback",
                name="tasktype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("patient_id", sa.Uuid(), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum(
                "booked",
                "confirmed",
                "rescheduled",
                "cancelled",
                "refused",
                "thinking",
                "callback",
                "no_answer",
                "wrong_number",
                "do_not_call",
                "done",
                name="outcome",
                native_enum=False,
                length=15,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=50), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_task_attempts_created_at"), "task_attempts", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_task_attempts_outcome"), "task_attempts", ["outcome"], unique=False)
    op.create_index(op.f("ix_task_attempts_task_id"), "task_attempts", ["task_id"], unique=False)
    op.create_index(
        op.f("ix_task_attempts_task_type"), "task_attempts", ["task_type"], unique=False
    )
    op.create_index(op.f("ix_task_attempts_user_id"), "task_attempts", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_attempts_user_id"), table_name="task_attempts")
    op.drop_index(op.f("ix_task_attempts_task_type"), table_name="task_attempts")
    op.drop_index(op.f("ix_task_attempts_task_id"), table_name="task_attempts")
    op.drop_index(op.f("ix_task_attempts_outcome"), table_name="task_attempts")
    op.drop_index(op.f("ix_task_attempts_created_at"), table_name="task_attempts")
    op.drop_table("task_attempts")
    op.drop_index(op.f("ix_tasks_type"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_patient_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_lead_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_due_at"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_campaign_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_leads_stage"), table_name="leads")
    op.drop_index(op.f("ix_leads_sla_due_at"), table_name="leads")
    op.drop_index(op.f("ix_leads_phone"), table_name="leads")
    op.drop_index(op.f("ix_leads_patient_id"), table_name="leads")
    op.drop_index(op.f("ix_leads_channel"), table_name="leads")
    op.drop_table("leads")
    op.drop_index(op.f("ix_shift_notes_created_at"), table_name="shift_notes")
    op.drop_table("shift_notes")
    op.drop_index(op.f("ix_scripts_code"), table_name="scripts")
    op.drop_table("scripts")
    op.drop_index(op.f("ix_campaigns_status"), table_name="campaigns")
    op.drop_table("campaigns")
    # ### end Alembic commands ###
