"""diagnosis mappings

Revision ID: db56de25ced6
Revises: 0f32b5776a50
Create Date: 2026-09-26 19:25:00.704168
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "db56de25ced6"
down_revision: str | None = "0f32b5776a50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diagnosis_mappings",
        sa.Column("text", sa.String(length=500), nullable=False),
        sa.Column("category_code", sa.String(length=50), nullable=True),
        sa.Column(
            "method",
            sa.Enum("rule", "ai", "manual", name="mappingmethod", native_enum=False, length=10),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "suggested",
                "approved",
                name="mappingstatus",
                native_enum=False,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["approved_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("text"),
    )
    op.create_index(
        op.f("ix_diagnosis_mappings_category_code"),
        "diagnosis_mappings",
        ["category_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_diagnosis_mappings_status"), "diagnosis_mappings", ["status"], unique=False
    )
    op.add_column("patient_conditions", sa.Column("text_key", sa.String(length=500), nullable=True))
    op.create_index(
        op.f("ix_patient_conditions_text_key"), "patient_conditions", ["text_key"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_patient_conditions_text_key"), table_name="patient_conditions")
    op.drop_column("patient_conditions", "text_key")
    op.drop_index(op.f("ix_diagnosis_mappings_status"), table_name="diagnosis_mappings")
    op.drop_index(op.f("ix_diagnosis_mappings_category_code"), table_name="diagnosis_mappings")
    op.drop_table("diagnosis_mappings")
    # ### end Alembic commands ###
