"""patients

Revision ID: 52a045ca73cb
Revises: 6b26347cf75d
Create Date: 2026-09-26 18:48:59.474004
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "52a045ca73cb"
down_revision: str | None = "6b26347cf75d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # trigram indexes for script-insensitive name search and partial phone search
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patients",
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("search_key", sa.String(length=255), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column(
            "gender",
            sa.Enum("male", "female", "unknown", name="gender", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("district", sa.String(length=100), nullable=True),
        sa.Column(
            "language",
            sa.Enum("uz", "ru", name="language", native_enum=False, length=5),
            nullable=False,
        ),
        sa.Column(
            "kind",
            sa.Enum(
                "active", "legacy", "cold", "lead", name="patientkind", native_enum=False, length=10
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "instagram",
                "telegram",
                "google",
                "maps",
                "website",
                "recommendation",
                "advertising",
                "returning",
                "import",
                "cold_base",
                "other",
                name="source",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("tags", postgresql.ARRAY(sa.String(length=50)), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("do_not_call", sa.Boolean(), nullable=False),
        sa.Column("do_not_call_reason", sa.String(length=255), nullable=True),
        sa.Column("last_visit_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("legacy_ref", sa.String(length=100), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("merged_into_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["merged_into_id"], ["patients.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_patients_district"), "patients", ["district"], unique=False)
    op.create_index(op.f("ix_patients_kind"), "patients", ["kind"], unique=False)
    op.create_index(op.f("ix_patients_legacy_ref"), "patients", ["legacy_ref"], unique=False)
    op.create_index(
        op.f("ix_patients_merged_into_id"), "patients", ["merged_into_id"], unique=False
    )
    op.create_index(
        "ix_patients_search_key_trgm",
        "patients",
        ["search_key"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"search_key": "gin_trgm_ops"},
    )
    op.create_table(
        "patient_phones",
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=16), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("note", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_patient_phones_number", "patient_phones", ["number"], unique=False)
    op.create_index(
        "ix_patient_phones_number_trgm",
        "patient_phones",
        ["number"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"number": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("ix_patient_phones_patient_id"), "patient_phones", ["patient_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_patient_phones_patient_id"), table_name="patient_phones")
    op.drop_index(
        "ix_patient_phones_number_trgm",
        table_name="patient_phones",
        postgresql_using="gin",
        postgresql_ops={"number": "gin_trgm_ops"},
    )
    op.drop_index("ix_patient_phones_number", table_name="patient_phones")
    op.drop_table("patient_phones")
    op.drop_index(
        "ix_patients_search_key_trgm",
        table_name="patients",
        postgresql_using="gin",
        postgresql_ops={"search_key": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_patients_merged_into_id"), table_name="patients")
    op.drop_index(op.f("ix_patients_legacy_ref"), table_name="patients")
    op.drop_index(op.f("ix_patients_kind"), table_name="patients")
    op.drop_index(op.f("ix_patients_district"), table_name="patients")
    op.drop_table("patients")
    # ### end Alembic commands ###
