"""catalog and scheduling

Revision ID: 5fc0390e31aa
Revises: db56de25ced6
Create Date: 2026-09-26 19:43:00.791488
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5fc0390e31aa"
down_revision: str | None = "db56de25ced6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # EXCLUDE constraints combine uuid equality with range overlap -> needs btree_gist
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "branches",
        sa.Column("site_id", sa.String(length=64), nullable=True),
        sa.Column("name_uz", sa.String(length=255), nullable=False),
        sa.Column("name_ru", sa.String(length=255), nullable=False),
        sa.Column("address_uz", sa.String(length=500), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("is_main", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id"),
    )
    op.create_table(
        "service_categories",
        sa.Column("site_id", sa.String(length=100), nullable=False),
        sa.Column("name_uz", sa.String(length=255), nullable=False),
        sa.Column("name_ru", sa.String(length=255), nullable=False),
        sa.Column(
            "specialty",
            sa.Enum(
                "dermatologist",
                "trichologist",
                "cosmetologist",
                "oncodermatologist",
                "podologist",
                name="specialty",
                native_enum=False,
                length=30,
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id"),
    )
    op.create_table(
        "doctors",
        sa.Column("site_id", sa.String(length=64), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("name_uz", sa.String(length=255), nullable=False),
        sa.Column("name_ru", sa.String(length=255), nullable=False),
        sa.Column("title_uz", sa.String(length=255), nullable=True),
        sa.Column("title_ru", sa.String(length=255), nullable=True),
        sa.Column("specialties", postgresql.ARRAY(sa.String(length=30)), nullable=False),
        sa.Column("color", sa.String(length=9), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "resources",
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("room", "device", name="resourcekind", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("device_type", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_resources_branch_id"), "resources", ["branch_id"], unique=False)
    op.create_index(op.f("ix_resources_device_type"), "resources", ["device_type"], unique=False)
    op.create_table(
        "services",
        sa.Column("site_id", sa.String(length=64), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("name_uz", sa.String(length=500), nullable=False),
        sa.Column("name_ru", sa.String(length=500), nullable=False),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("duration_min", sa.Integer(), nullable=False),
        sa.Column("device_type", sa.String(length=50), nullable=True),
        sa.Column("requires_consultation", sa.Boolean(), nullable=False),
        sa.Column("is_consultation", sa.Boolean(), nullable=False),
        sa.Column("course_sessions", sa.Integer(), nullable=True),
        sa.Column("min_interval_days", sa.Integer(), nullable=True),
        sa.Column("followup_call_days", sa.Integer(), nullable=True),
        sa.Column("prep_uz", sa.Text(), nullable=True),
        sa.Column("prep_ru", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["service_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id"),
    )
    op.create_index(op.f("ix_services_category_id"), "services", ["category_id"], unique=False)
    op.create_table(
        "appointments",
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("doctor_id", sa.Uuid(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "during",
            postgresql.TSTZRANGE(),
            sa.Computed("tstzrange(starts_at, ends_at)", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "scheduled",
                "confirmed",
                "arrived",
                "completed",
                "no_show",
                "cancelled",
                "rescheduled",
                name="appointmentstatus",
                native_enum=False,
                length=12,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "instagram",
                "telegram",
                "google",
                "maps",
                "website",
                "recommendation",
                "advertising",
                "returning",
                "import",
                "cold_base",
                "other",
                name="source",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("cancel_reason", sa.String(length=100), nullable=True),
        sa.Column("rescheduled_from_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("status_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        postgresql.ExcludeConstraint(
            (sa.column("doctor_id"), "="),
            (sa.column("during"), "&&"),
            where=sa.text("status IN ('scheduled', 'confirmed', 'arrived', 'completed')"),
            using="gist",
            name="no_doctor_overlap",
        ),
        postgresql.ExcludeConstraint(
            (sa.column("resource_id"), "="),
            (sa.column("during"), "&&"),
            where=sa.text(
                "resource_id IS NOT NULL AND status IN ('scheduled', 'confirmed', 'arrived', 'completed')"
            ),
            using="gist",
            name="no_resource_overlap",
        ),
        sa.CheckConstraint("starts_at < ends_at", name="starts_before_ends"),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(["rescheduled_from_id"], ["appointments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_appointments_branch_id"), "appointments", ["branch_id"], unique=False)
    op.create_index(op.f("ix_appointments_doctor_id"), "appointments", ["doctor_id"], unique=False)
    op.create_index(
        op.f("ix_appointments_patient_id"), "appointments", ["patient_id"], unique=False
    )
    op.create_index(op.f("ix_appointments_starts_at"), "appointments", ["starts_at"], unique=False)
    op.create_index(op.f("ix_appointments_status"), "appointments", ["status"], unique=False)
    op.create_table(
        "doctor_absences",
        sa.Column("doctor_id", sa.Uuid(), nullable=False),
        sa.Column("date_from", sa.Date(), nullable=False),
        sa.Column("date_to", sa.Date(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("date_from <= date_to", name="from_before_to"),
        sa.ForeignKeyConstraint(["doctor_id"], ["doctors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_doctor_absences_doctor_id"), "doctor_absences", ["doctor_id"], unique=False
    )
    op.create_table(
        "doctor_schedules",
        sa.Column("doctor_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("weekday", sa.SmallInteger(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("start_time < end_time", name="start_before_end"),
        sa.CheckConstraint("weekday BETWEEN 0 AND 6", name="weekday_range"),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(["doctor_id"], ["doctors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_doctor_schedules_doctor_id"), "doctor_schedules", ["doctor_id"], unique=False
    )
    op.create_table(
        "doctor_services",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("doctor_id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["doctor_id"], ["doctors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doctor_id", "service_id"),
    )
    op.create_table(
        "appointment_services",
        sa.Column("appointment_id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("duration_min", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["appointment_id"], ["appointments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_appointment_services_appointment_id"),
        "appointment_services",
        ["appointment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_appointment_services_service_id"),
        "appointment_services",
        ["service_id"],
        unique=False,
    )
    op.create_table(
        "recommendations",
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("doctor_id", sa.Uuid(), nullable=True),
        sa.Column("appointment_id", sa.Uuid(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "booked",
                "dismissed",
                name="recommendationstatus",
                native_enum=False,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["appointment_id"], ["appointments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recommendations_due_date"), "recommendations", ["due_date"], unique=False
    )
    op.create_index(
        op.f("ix_recommendations_patient_id"), "recommendations", ["patient_id"], unique=False
    )
    op.create_index(op.f("ix_recommendations_status"), "recommendations", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recommendations_status"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_patient_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_due_date"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_appointment_services_service_id"), table_name="appointment_services")
    op.drop_index(op.f("ix_appointment_services_appointment_id"), table_name="appointment_services")
    op.drop_table("appointment_services")
    op.drop_table("doctor_services")
    op.drop_index(op.f("ix_doctor_schedules_doctor_id"), table_name="doctor_schedules")
    op.drop_table("doctor_schedules")
    op.drop_index(op.f("ix_doctor_absences_doctor_id"), table_name="doctor_absences")
    op.drop_table("doctor_absences")
    op.drop_index(op.f("ix_appointments_status"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_starts_at"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_patient_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_doctor_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_branch_id"), table_name="appointments")
    op.drop_table("appointments")
    op.drop_index(op.f("ix_services_category_id"), table_name="services")
    op.drop_table("services")
    op.drop_index(op.f("ix_resources_device_type"), table_name="resources")
    op.drop_index(op.f("ix_resources_branch_id"), table_name="resources")
    op.drop_table("resources")
    op.drop_table("doctors")
    op.drop_table("service_categories")
    op.drop_table("branches")
    # ### end Alembic commands ###
