
[@@EXT@@]
type=endpoint
context=from-operators
disallow=all
allow=ulaw,alaw
webrtc=yes
dtls_auto_generate_cert=yes
direct_media=no
device_state_busy_at=1
auth=@@EXT@@
aors=@@EXT@@
callerid=Operator <@@EXT@@>

[@@EXT@@]
type=auth
auth_type=userpass
username=@@EXT@@
password=@@EXT_PASSWORD@@

[@@EXT@@]
type=aor
max_contacts=1
remove_existing=yes
qualify_frequency=30
